FROM ubuntu:18.04 as harsha
RUN apt update && apt install unzip -y
ADD https://github.com/nopSolutions/nopCommerce/releases/download/release-4.40.2/nopCommerce_4.40.2_NoSource_linux_x64.zip /nop/nopCommerce_4.40.2_NoSource_linux_x64.zip
RUN cd nop && unzip nopCommerce_4.40.2_NoSource_linux_x64.zip




FROM mcr.microsoft.com/dotnet/aspnet:5.0

LABEL author="sanjeev"
LABEL company="andhagadu"
COPY --from=harsha /nop /nop-bin
CMD [ "dotnet", "/nop-bin/Nop.Web.dll" ]

EXPOSE 80
WORKDIR /nop-bin
