---
apiVersion: v1
kind: Pod
metadata:
  name: label-demo3
  labels:
    environment: developer
    team: system-ops
    project: qt-shopping
spec:
  containers:
    - name: mysql-container
      image: mysql
      ports:
        - containerPort: 3306
          protocol: TCP 