---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-vol-demo
spec:
  containers:
    - image: alpine
      name: alpine-container
      args:
       - /bin/sh
       - -c
       - sleep 1d
      volumeMounts:
        - name: config-sanju
          mountPath: /etc/appconfig
  volumes:
    - name: config-sanju
      configMap:
        name: sanju-dest